[package]
name = "redis-lbucket"
description = "Redis module that implements leaky bucket algorithm"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"
repository = "https://github.com/realaravinth/redis-leaky-bucket"
license = "AGPLv3 or later version"

[lib]
crate-type = ["cdylib"]
name = "lbucket"

[dependencies]
redis-module = { version="0.17", features = ["experimental-api"]}
libc = "0.2"
serde_json = "1.0.64"
serde = {version = "1.0.126", features = ["derive"]}
lazy_static = "1.4.0"
rand = "0.8.3"

#[target.x86_64-unknown-linux-musl]
#linker = "cc"

[features]
test = ["redis-module/test"]
